export const authConstants ={

    AUTHENTICATION_REQUEST:"AUTHENTICATION_REQUEST",
    AUTHENTICATION_SUCCESS:"AUTHENTICATION_SUCCESS",
    AUTHENTICATION_FAILURE:"AUTHENTICATION_FAILURE",

   /* LOGIN_REQUEST :"LOGIN_REQUEST",
    LOGIN_SUCCESS :"LOGIN_SUCCESS",
    LOGIN_FAILURE :"LOGIN_FAILURE",
    */
    LOGOUT :"LOGOUT",

    REGISTER_REQUEST:"REGISTER_REQUEST",
    REGISTER_SUCCESS:"REGISTER_SUCCESS",
    REGISTER_FAILURE:"REGISTER_FAILURE"
};

